name: Build and Deploy Research Agent API
on:
  push:
    branches: [ main ]
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  SERVICE_NAME: research-agent-api
  REGISTRY_HOSTNAME: us-central1-docker.pkg.dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGISTRY_HOSTNAME }}
      - name: Build and Push Docker Image
        run: |-
          docker build -t ${{ env.REGISTRY_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/api:latest .
          docker push ${{ env.REGISTRY_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/api:latest
      - name: Deploy to Google Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.GCP_REGION }}
          image: ${{ env.REGISTRY_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/api:latest
          env_vars:
            LANGCHAIN_TRACING_V2: "true"
            LANGCHAIN_PROJECT: "Production Research Agent"
          secrets:
            GOOGLE_API_KEY: GOOGLE_API_KEY:latest
            LANGCHAIN_API_KEY: LANGCHAIN_API_KEY:latest